Feature/profile dropdown
Dhruvi-Makwana/Chatify pull request #10
Opened 2023-05-03 11:15 UTC by Dhruvi-Makwana

2023-05-03 11:21 UTC, yatishTrootech requested changes

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/models.py
> +    online = models.BooleanField(default=False)
add 1 line only

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/static/js/chat.js
> +          $scope.status = 'online';
All should be on top $scope.status = 'online';

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/static/js/chat.js
> +          console.log(status)
proper indentation

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/static/js/chat.js
> +          }
remove console

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/static/js/register.js
> + $(document).on("submit", "#register_form", function(event) {
wrap up in a function don't register events

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/templates/chat/base.html
> +        <link rel="stylesheet" href="{% static 'css/register.css' %}">
<link rel="stylesheet" href="{% static 'css/register.css' %}"> should be in register html page

2023-05-03 11:21 UTC, yatishTrootech commented on Chatify/chat/templates/chat/register.html
> + <script src="{% static 'js/ajax_request.js' %}"></script>
<script src="{% static 'js/ajax_request.js' %}"></script> should be in base.js

2023-05-04 04:47 UTC, yatishTT requested changes

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/api.py
> +    def put(self, request, *args, **kwargs):
def post

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/api.py
> +        if request.data.get("online") == "true":
user.save(online=True if request.data.get("online") else False)

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/api.py
> +        return Response(status=status.HTTP_400_BAD_REQUEST)
why 400 on success ?

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/models.py
> +    online = models.BooleanField(default=False, blank=True, null=True)
boolean flag starts from is > is_online

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/serializers.py
> +            "online",
is_online

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/static/css/chat.css
> +        }
wrong indentation

2023-05-04 04:47 UTC, yatishTT commented on Chatify/chat/templates/chat/chat.html
> +                        <span>Dhruvi</span>
why name and DP is static ?

2023-05-04 06:24 UTC, merged