Feature/registration data binding
Dhruvi-Makwana/Chatify pull request #12
Opened 2023-05-08 05:39 UTC by HARSHKALAL

2023-05-08 10:22 UTC, yatishTrootech requested changes

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/api.py
> +            serializer = UserSerializer(data=set_contact_number(request.data))
phone number should validated from  ```validate_phone_nuber``` method

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/static/js/ajax_request.js
> +            console.log(data)
Show error dont console

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/static/js/register.js
> +        console.log("Ajax call")
remove console @Dhruvi-Makwana Why you have not added comment ?

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/static/js/register.js
> +        makeAjaxRequest('POST', csrfToken, "http://127.0.0.1:8000/api/register/", formdata, function (response) {
Why full URL? @Dhruvi-Makwana Why comment not added by you ?

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/utils.py
> +def set_contact_number(data):
def validate_phone_number

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/utils.py
> +    get_mobile_number = data.get("mobile_number")
wrong variable name

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/utils.py
> +    elif len(get_mobile_number) == 10:
it will fail for "+912332323"

2023-05-08 10:22 UTC, yatishTrootech commented on Chatify/chat/utils.py
> +        data["mobile_number"] = "+91" + get_mobile_number
what if i pass 20 length mobile number ?

2023-05-09 09:27 UTC, Dhruvi-Makwana commented on Chatify/chat/serializers.py
> +        breakpoint()
remove breakpoint()

2023-05-09 09:28 UTC, Dhruvi-Makwana commented on Chatify/chat/urls.py
> +    path("api/register/", RegistrationApi.as_view(), name="api/register/"),
is it correct name for this url ? don;t we simply write "RegistrationApi".

2023-05-09 13:27 UTC, yatishTT approved these changes

2023-05-09 13:27 UTC, yatishTT commented on Chatify/chat/serializers.py
> +        breakpoint()
why breakpoint is there ?>

2023-05-09 13:27 UTC, yatishTT commented on Chatify/chat/serializers.py
> +        return mobile_number
return validate_contact_number(mobile_number) from utils

2023-05-09 13:27 UTC, merged