Feature/websocket
Dhruvi-Makwana/Chatify pull request #13
Opened 2023-05-08 12:36 UTC by Dhruvi-Makwana

2023-05-08 12:43 UTC, Dhruvi-Makwana commented on Chatify/chat/static/js/register.js
> +             console.log(response)
please remove console.log !!

2023-05-08 12:43 UTC, Dhruvi-Makwana commented on Chatify/chat/api.py
> +from .utils import *
don't use * use proper name

2023-05-09 08:05 UTC, yatishTT requested changes

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/api.py
> +        login_serializer.is_valid()
is_valid(raise_exception=True)

use try except

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/api.py
> +                login_serializer.errors, status=status.HTTP_406_NOT_ACCEPTABLE
400 bad request

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/api.py
> +        return Response(status=status.HTTP_200_OK)
don't need for get method

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/api.py
> +        data = request.data.copy()
no need of copy

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/api.py
> +        user.is_online = (
user.is_online = data.get("online") is not None or False

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/api.py
> +            {"UserData": list(GetUserDataSerializer(data, many=True).data)}
UserDataSerializer

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/consumers.py
> +class MyChatConsumer(SyncConsumer):
What is myconsumer ?

2023-05-09 08:05 UTC, yatishTT commented on Chatify/chat/static/js/chat.js
> +        $http.get(url).then(function(response) {
use our ajax funciton

2023-05-09 10:04 UTC, Dhruvi-Makwana commented on Chatify/chat/static/js/chat.js
> +        $http.get(url).then(function(response) {
in this js we using angular JS so it's better to create here ajaxGet.

2023-05-09 10:04 UTC, Dhruvi-Makwana commented on Chatify/chat/consumers.py
> +        print("message Recevied", event)
remove print statement

2023-05-09 10:04 UTC, Dhruvi-Makwana commented on Chatify/chat/static/js/register.js
> +                    $("#phonenumber").html(number);
Is it  working properly ?

2023-05-09 10:04 UTC, Dhruvi-Makwana commented on Chatify/chat/templates/chat/register.html
> +      <div class="signup-link">Already a user ?..<a href="{% url 'chat:loginUI' %}">Login</a></div>
is it require to write a app name

2023-05-09 10:12 UTC, Dhruvi-Makwana commented on Chatify/chat/static/js/register.js
> +                    $("#phonenumber").html(number);
yes

2023-05-09 10:12 UTC, Dhruvi-Makwana commented on Chatify/chat/templates/chat/register.html
> +      <div class="signup-link">Already a user ?..<a href="{% url 'chat:loginUI' %}">Login</a></div>
yes without that it shows error.

2023-05-09 10:13 UTC, Dhruvi-Makwana commented on Chatify/chat/consumers.py
> +class MyChatConsumer(SyncConsumer):
sir it's just function name harsh_kalal change according to requirement

2023-05-12 04:46 UTC, closed without merging