chat template file created
Dhruvi-Makwana/Chatify pull request #4
Opened 2023-04-26 09:20 UTC by HARSHKALAL

2023-04-26 12:24 UTC, Dhruvi-Makwana commented on Chatify/chat/views.py
>      return render(request,"chat/chat.html")
add new line

2023-04-26 12:25 UTC, Dhruvi-Makwana commented on Chatify/chat/urls.py
> +]
add new  line at end of file

2023-04-26 12:27 UTC, Dhruvi-Makwana commented on Chatify/chat/urls.py
>  ]
add new line at end of file, 
url name is not proper

2023-04-27 06:38 UTC, yatishTrootech requested changes

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/Chatify/settings/base.py
> +        "PORT": "",
Port should not be blank

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/static/css/register.css
> +}
add a line at the end of file

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
Don;t use CDN

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +    <div class="container-fluid h-100">
Code should not be repeated use ANGULAR JS to bind users in array

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +                            <div class="img_cont_msg">
Messages Should be from ANgular JS araay

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +                                <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMWFhUXGBgaGBcXFxgXFxgdFxcXHRcXGhcYHSggGBolHRYVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGhAQGy
don't Use base 64 instead use a link

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/login.html
> +      </div>
Don;t submit form directly it should be submitted by login.JS AJAX

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/register.html
>  <html lang="en" dir="ltr">
Add register.JS

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +    <title>Chat</title>
Add a http_utils.JS
Add ajax code there

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +<head>
Every JS which is linked with html should be a Angular JS controller file

2023-04-27 06:38 UTC, yatishTrootech commented on Chatify/chat/templates/chat/chat.html
> +    <link rel="stylesheet" type="text/css"
No HTML will have JS code

2023-04-27 07:39 UTC, closed without merging