Add/angular binding in chat
Dhruvi-Makwana/Chatify pull request #8
Opened 2023-05-01 13:01 UTC by Dhruvi-Makwana

2023-05-02 12:10 UTC, yatishTT requested changes

2023-05-02 12:10 UTC, yatishTT commented on Chatify/chat/static/js/chat.js
> +        console.log($scope.chatData)
remove console

2023-05-02 12:10 UTC, yatishTT commented on Chatify/chat/static/js/chat.js
> +            console.log($scope.currentUser)
remove concole

2023-05-02 12:10 UTC, yatishTT commented on Chatify/chat/static/js/chat.js
> +        alert($scope.msgText)
remove logs console alert

2023-05-02 12:10 UTC, yatishTT commented on Chatify/chat/static/js/chat.js
> +        var a = $scope.chatData[1].id
it should be dynamic

2023-05-02 12:10 UTC, yatishTT commented on Chatify/chat/static/js/chat.js
> +            $scope.chatData[1].messages.sender.push(message);
no static conditions should be there

2023-05-02 12:10 UTC, yatishTT commented on Chatify/chat/static/js/register.js
> + $(document).on("submit", "#register_form", function(event) {
use fucntions instead of event

2023-05-02 12:17 UTC, HARSHKALAL commented on Chatify/chat/static/js/chat.js
> +
why are you leaving 2 lines between two statemens

2023-05-03 11:36 UTC, yatishTrootech approved these changes

2023-05-03 11:37 UTC, merged